# Generated by Django 3.1.2 on 2020-10-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.rubro', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
