# Generated by Django 3.1.2 on 2020-11-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(default='0', max_length=100, verbose_name='Codigo Producto'),
        ),
    ]
