# Generated by Django 3.1.2 on 2020-11-11 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 22, 14, 40, 557179), verbose_name='Fecha Vencimiento'),
        ),
    ]
