# Generated by Django 3.1.2 on 2020-11-11 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201110_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 1, 15, 1, 854264, tzinfo=utc), verbose_name='Fecha Vencimiento'),
        ),
    ]
