# Generated by Django 3.1.2 on 2020-11-11 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('producto', '0005_auto_20201110_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2020, 11, 11, 4, 10, 9, 14977, tzinfo=utc), verbose_name='Fecha Vencimiento'),
        ),
    ]
